version: '3.8'

networks:
  traefik-web:
    external: true

services:
  router:
    image: syncra/router:${ROUTER_VERSION}
    container_name: syncra_router
    restart: unless-stopped
    environment:
      SPRING_RABBITMQ_HOST: ${RABBIT_HOST}
      RABBIT_HOST: ${RABBIT_HOST}
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
      RABBIT_VHOST: ${RABBIT_VHOST}
    networks:
      - traefik-web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncra_router.rule=Host(`api-router.syncra.me`)"
      - "traefik.http.routers.syncra_router.entrypoints=http"
      - "traefik.http.services.syncra_router.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik-web"
    expose:
      - 80
    volumes:
      - /syncra/logs/router:/app/logs