version: '3.8'

services:
  parser:
    image: "./syncra_parser"
    container_name: syncra_parser
    environment:
      SPRING_RABBITMQ_HOST: ${RABBIT_HOST}
      RABBIT_HOST: ${RABBIT_HOST}
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
      CORE_URL: ${CORE_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myapp.rule=Host(`parser.syncra.me`)"
      - "traefik.http.routers.myapp.entrypoints=websecure"
      - "traefik.http.routers.myapp.tls.certresolver=myresolver"

  router:
    build: "./syncra_router"
    container_name: syncra_router
    environment:
      SPRING_RABBITMQ_HOST: ${RABBIT_HOST}
      RABBIT_HOST: ${RABBIT_HOST}
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myapp.rule=Host(`router.syncra.me`)"
      - "traefik.http.routers.myapp.entrypoints=websecure"
      - "traefik.http.routers.myapp.tls.certresolver=myresolver"
