name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: "Set version of Syncra Router"
        required: true
        default: "1.0.0"

env:
  DIR: syncra_router

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Tests
        run: ./gradlew clean test

  build:
    name: Build and Deploy Docker Image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version
        id: set_version
        run: |
          echo "ROUTER_VERSION=${{ github.event.inputs.version || '1.0.0' }}" >> $GITHUB_ENV

      - name: Create project dir
        run: |
          echo "${{ secrets.SSH_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -i key.pem ${{ secrets.USER }}@${{ secrets.HOST }} -p ${{ secrets.SSH_PORT }} << 'EOF'
             sudo mkdir -p /syncra/${{ env.DIR }} && sudo chown -R ${{ secrets.USER }}:${{ secrets.USER }} /syncra/${{ env.DIR }}
          EOF

      - name: Build Docker Image
        run: |
          docker build . -t syncra/router:${{ env.ROUTER_VERSION }}
          docker save -o router.tar syncra/router:${{ env.ROUTER_VERSION }}

      - name: Copy Image to Server
        run: |
          echo "${{ secrets.SSH_KEY }}" > key.pem
          chmod 600 key.pem
          scp -P ${{ secrets.SSH_PORT }} -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -i key.pem router.tar ${{ secrets.USER }}@${{ secrets.HOST }}:/${{ secrets.USER }}/${{ env.DIR }}

      - name: Create .env file on Server
        run: |
          echo "ROUTER_VERSION=${{ github.event.inputs.version || '1.0.0' }}" > .env
          echo "RABBIT_HOST=${{ secrets.RABBIT_HOST }}" >> .env
          echo "RABBIT_PORT=${{ secrets.RABBIT_PORT }}" >> .env
          echo "RABBIT_USER=${{ secrets.RABBIT_USER }}" >> .env
          echo "RABBIT_VHOST=${{ secrets.RABBIT_VHOST }}" >> .env
          echo "RABBIT_PASSWORD=${{ secrets.RABBIT_PASSWORD }}" >> .env
          echo "${{ secrets.SSH_KEY }}" > key.pem
          chmod 600 key.pem
          scp -P ${{ secrets.SSH_PORT }} -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -i key.pem .env ${{ secrets.USER }}@${{ secrets.HOST }}:/${{ secrets.USER }}/${{ env.DIR }}

      - name: Load Container
        run: |
          echo "${{ secrets.SSH_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -i key.pem ${{ secrets.USER }}@${{ secrets.HOST }} -p ${{ secrets.SSH_PORT }} << 'EOF'
            sudo docker load -i /${{ secrets.USER }}/${{ env.DIR }}/router.tar
          EOF

      - name: Copy docker-compose.yml to Server
        run: |
          echo "${{ secrets.SSH_KEY }}" > key.pem
          chmod 600 key.pem
          scp -P ${{ secrets.SSH_PORT }} -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -i key.pem docker-compose.yml ${{ secrets.USER }}@${{ secrets.HOST }}:/${{ secrets.USER }}/${{ env.DIR }}

      - name: Restart Docker Compose
        run: |
          echo "${{ secrets.SSH_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -i key.pem ${{ secrets.USER }}@${{ secrets.HOST }} -p ${{ secrets.SSH_PORT }} << 'EOF'
            cd /${{ secrets.USER }}/${{ env.DIR }}
            source .env
            sudo docker-compose down -v
            sudo docker-compose up -d --build
          EOF